apiVersion: v2  
name: cursus
description: lightweight message broker 
type: application  
version: 0.1.0  
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/downfa11-org/cursus/main/.github/cursus.png