apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: {{ include "cursus.fullname" . }}-logs  
spec:  
  storageClassName: {{ .Values.persistence.storageClass | default "" }}  
  accessModes:  
    - ReadWriteOnce
  resources:  
    requests:  
      storage: 1Gi