apiVersion: v1
entries:
  cursus:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-12-23T17:29:46.6945122+09:00"
    description: an lightweight message broker
    digest: bc26b65e4d8f7e38711e93930a8acf75fd1a4548eada61ef4d5929bd93fb655e
    icon: https://github.com/downfa11-org/cursus/blob/main/.github/cursus.png
    name: cursus
    type: application
    urls:
    - https://downfa11-org.github.io/cursus/manifests/charts/cursus-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-23T17:29:46.6927187+09:00"
